	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_wave_54::
	.incbin "sound/direct_sound_samples/wave_54.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_wave_56::
	.incbin "sound/direct_sound_samples/wave_56.bin"

	.align 2
DirectSoundWaveData_wave_57::
	.incbin "sound/direct_sound_samples/wave_57.bin"

	.align 2
DirectSoundWaveData_wave_58::
	.incbin "sound/direct_sound_samples/wave_58.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_wave_61::
	.incbin "sound/direct_sound_samples/wave_61.bin"

	.align 2
DirectSoundWaveData_wave_62::
	.incbin "sound/direct_sound_samples/wave_62.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_wave_64::
	.incbin "sound/direct_sound_samples/wave_64.bin"

	.align 2
DirectSoundWaveData_wave_65::
	.incbin "sound/direct_sound_samples/wave_65.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_wave_68::
	.incbin "sound/direct_sound_samples/wave_68.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_wave_72::
	.incbin "sound/direct_sound_samples/wave_72.bin"

	.align 2
DirectSoundWaveData_wave_73::
	.incbin "sound/direct_sound_samples/wave_73.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"


	.align 2
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cries/bulbasaur.bin"

	.align 2
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cries/ivysaur.bin"

	.align 2
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cries/venusaur.bin"

	.align 2
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cries/charmander.bin"

	.align 2
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cries/charmeleon.bin"

	.align 2
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cries/charizard.bin"

	.align 2
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cries/squirtle.bin"

	.align 2
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cries/wartortle.bin"

	.align 2
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cries/blastoise.bin"

	.align 2
Cry_Caterpie::
	.incbin "sound/direct_sound_samples/cries/caterpie.bin"

	.align 2
Cry_Metapod::
	.incbin "sound/direct_sound_samples/cries/metapod.bin"

	.align 2
Cry_Butterfree::
	.incbin "sound/direct_sound_samples/cries/butterfree.bin"

	.align 2
Cry_Weedle::
	.incbin "sound/direct_sound_samples/cries/weedle.bin"

	.align 2
Cry_Kakuna::
	.incbin "sound/direct_sound_samples/cries/kakuna.bin"

	.align 2
Cry_Beedrill::
	.incbin "sound/direct_sound_samples/cries/beedrill.bin"

	.align 2
Cry_Pidgey::
	.incbin "sound/direct_sound_samples/cries/pidgey.bin"

	.align 2
Cry_Pidgeotto::
	.incbin "sound/direct_sound_samples/cries/pidgeotto.bin"

	.align 2
Cry_Pidgeot::
	.incbin "sound/direct_sound_samples/cries/pidgeot.bin"

	.align 2
Cry_Rattata::
	.incbin "sound/direct_sound_samples/cries/rattata.bin"

	.align 2
Cry_Raticate::
	.incbin "sound/direct_sound_samples/cries/raticate.bin"

	.align 2
Cry_Spearow::
	.incbin "sound/direct_sound_samples/cries/spearow.bin"

	.align 2
Cry_Fearow::
	.incbin "sound/direct_sound_samples/cries/fearow.bin"

	.align 2
Cry_Ekans::
	.incbin "sound/direct_sound_samples/cries/ekans.bin"

	.align 2
Cry_Arbok::
	.incbin "sound/direct_sound_samples/cries/arbok.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cries/pikachu.bin"

	.align 2
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cries/raichu.bin"

	.align 2
Cry_Sandshrew::
	.incbin "sound/direct_sound_samples/cries/sandshrew.bin"

	.align 2
Cry_Sandslash::
	.incbin "sound/direct_sound_samples/cries/sandslash.bin"

	.align 2
Cry_NidoranF::
	.incbin "sound/direct_sound_samples/cries/nidoran_f.bin"

	.align 2
Cry_Nidorina::
	.incbin "sound/direct_sound_samples/cries/nidorina.bin"

	.align 2
Cry_Nidoqueen::
	.incbin "sound/direct_sound_samples/cries/nidoqueen.bin"

	.align 2
Cry_NidoranM::
	.incbin "sound/direct_sound_samples/cries/nidoran_m.bin"

	.align 2
Cry_Nidorino::
	.incbin "sound/direct_sound_samples/cries/nidorino.bin"

	.align 2
Cry_Nidoking::
	.incbin "sound/direct_sound_samples/cries/nidoking.bin"

	.align 2
Cry_Clefairy::
	.incbin "sound/direct_sound_samples/cries/clefairy.bin"

	.align 2
Cry_Clefable::
	.incbin "sound/direct_sound_samples/cries/clefable.bin"

	.align 2
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cries/vulpix.bin"

	.align 2
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cries/ninetales.bin"

	.align 2
Cry_Jigglypuff::
	.incbin "sound/direct_sound_samples/cries/jigglypuff.bin"

	.align 2
Cry_Wigglytuff::
	.incbin "sound/direct_sound_samples/cries/wigglytuff.bin"

	.align 2
Cry_Zubat::
	.incbin "sound/direct_sound_samples/cries/zubat.bin"

	.align 2
Cry_Golbat::
	.incbin "sound/direct_sound_samples/cries/golbat.bin"

	.align 2
Cry_Oddish::
	.incbin "sound/direct_sound_samples/cries/oddish.bin"

	.align 2
Cry_Gloom::
	.incbin "sound/direct_sound_samples/cries/gloom.bin"

	.align 2
Cry_Vileplume::
	.incbin "sound/direct_sound_samples/cries/vileplume.bin"

	.align 2
Cry_Paras::
	.incbin "sound/direct_sound_samples/cries/paras.bin"

	.align 2
Cry_Parasect::
	.incbin "sound/direct_sound_samples/cries/parasect.bin"

	.align 2
Cry_Venonat::
	.incbin "sound/direct_sound_samples/cries/venonat.bin"

	.align 2
Cry_Venomoth::
	.incbin "sound/direct_sound_samples/cries/venomoth.bin"

	.align 2
Cry_Diglett::
	.incbin "sound/direct_sound_samples/cries/diglett.bin"

	.align 2
Cry_Dugtrio::
	.incbin "sound/direct_sound_samples/cries/dugtrio.bin"

	.align 2
Cry_Meowth::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Persian::
	.incbin "sound/direct_sound_samples/cries/persian.bin"

	.align 2
Cry_Psyduck::
	.incbin "sound/direct_sound_samples/cries/psyduck.bin"

	.align 2
Cry_Golduck::
	.incbin "sound/direct_sound_samples/cries/golduck.bin"

	.align 2
Cry_Mankey::
	.incbin "sound/direct_sound_samples/cries/mankey.bin"

	.align 2
Cry_Primeape::
	.incbin "sound/direct_sound_samples/cries/primeape.bin"

	.align 2
Cry_Growlithe::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Arcanine::
	.incbin "sound/direct_sound_samples/cries/arcanine.bin"

	.align 2
Cry_Poliwag::
	.incbin "sound/direct_sound_samples/cries/poliwag.bin"

	.align 2
Cry_Poliwhirl::
	.incbin "sound/direct_sound_samples/cries/poliwhirl.bin"

	.align 2
Cry_Poliwrath::
	.incbin "sound/direct_sound_samples/cries/poliwrath.bin"

	.align 2
Cry_Abra::
	.incbin "sound/direct_sound_samples/cries/abra.bin"

	.align 2
Cry_Kadabra::
	.incbin "sound/direct_sound_samples/cries/kadabra.bin"

	.align 2
Cry_Alakazam::
	.incbin "sound/direct_sound_samples/cries/alakazam.bin"

	.align 2
Cry_Machop::
	.incbin "sound/direct_sound_samples/cries/machop.bin"

	.align 2
Cry_Machoke::
	.incbin "sound/direct_sound_samples/cries/machoke.bin"

	.align 2
Cry_Machamp::
	.incbin "sound/direct_sound_samples/cries/machamp.bin"

	.align 2
Cry_Bellsprout::
	.incbin "sound/direct_sound_samples/cries/bellsprout.bin"

	.align 2
Cry_Weepinbell::
	.incbin "sound/direct_sound_samples/cries/weepinbell.bin"

	.align 2
Cry_Victreebel::
	.incbin "sound/direct_sound_samples/cries/victreebel.bin"

	.align 2
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cries/tentacool.bin"

	.align 2
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cries/tentacruel.bin"

	.align 2
Cry_Geodude::
	.incbin "sound/direct_sound_samples/cries/geodude.bin"

	.align 2
Cry_Graveler::
	.incbin "sound/direct_sound_samples/cries/graveler.bin"

	.align 2
Cry_Golem::
	.incbin "sound/direct_sound_samples/cries/golem.bin"

	.align 2
Cry_Ponyta::
	.incbin "sound/direct_sound_samples/cries/ponyta.bin"

	.align 2
Cry_Rapidash::
	.incbin "sound/direct_sound_samples/cries/rapidash.bin"

	.align 2
Cry_Slowpoke::
	.incbin "sound/direct_sound_samples/cries/slowpoke.bin"

	.align 2
Cry_Slowbro::
	.incbin "sound/direct_sound_samples/cries/slowbro.bin"

	.align 2
Cry_Magnemite::
	.incbin "sound/direct_sound_samples/cries/magnemite.bin"

	.align 2
Cry_Magneton::
	.incbin "sound/direct_sound_samples/cries/magneton.bin"

	.align 2
Cry_Farfetchd::
	.incbin "sound/direct_sound_samples/cries/farfetchd.bin"

	.align 2
Cry_Doduo::
	.incbin "sound/direct_sound_samples/cries/doduo.bin"

	.align 2
Cry_Dodrio::
	.incbin "sound/direct_sound_samples/cries/dodrio.bin"

	.align 2
Cry_Seel::
	.incbin "sound/direct_sound_samples/cries/seel.bin"

	.align 2
Cry_Dewgong::
	.incbin "sound/direct_sound_samples/cries/dewgong.bin"

	.align 2
Cry_Grimer::
	.incbin "sound/direct_sound_samples/cries/grimer.bin"

	.align 2
Cry_Muk::
	.incbin "sound/direct_sound_samples/cries/muk.bin"

	.align 2
Cry_Shellder::
	.incbin "sound/direct_sound_samples/cries/shellder.bin"

	.align 2
Cry_Cloyster::
	.incbin "sound/direct_sound_samples/cries/cloyster.bin"

	.align 2
Cry_Gastly::
	.incbin "sound/direct_sound_samples/cries/gastly.bin"

	.align 2
Cry_Haunter::
	.incbin "sound/direct_sound_samples/cries/haunter.bin"

	.align 2
Cry_Gengar::
	.incbin "sound/direct_sound_samples/cries/gengar.bin"

	.align 2
Cry_Onix::
	.incbin "sound/direct_sound_samples/cries/onix.bin"

	.align 2
Cry_Drowzee::
	.incbin "sound/direct_sound_samples/cries/drowzee.bin"

	.align 2
Cry_Hypno::
	.incbin "sound/direct_sound_samples/cries/hypno.bin"

	.align 2
Cry_Krabby::
	.incbin "sound/direct_sound_samples/cries/krabby.bin"

	.align 2
Cry_Kingler::
	.incbin "sound/direct_sound_samples/cries/kingler.bin"

	.align 2
Cry_Voltorb::
	.incbin "sound/direct_sound_samples/cries/voltorb.bin"

	.align 2
Cry_Electrode::
	.incbin "sound/direct_sound_samples/cries/electrode.bin"

	.align 2
Cry_Exeggcute::
	.incbin "sound/direct_sound_samples/cries/exeggcute.bin"

	.align 2
Cry_Exeggutor::
	.incbin "sound/direct_sound_samples/cries/exeggutor.bin"

	.align 2
Cry_Cubone::
	.incbin "sound/direct_sound_samples/cries/cubone.bin"

	.align 2
Cry_Marowak::
	.incbin "sound/direct_sound_samples/cries/marowak.bin"

	.align 2
Cry_Hitmonlee::
	.incbin "sound/direct_sound_samples/cries/hitmonlee.bin"

	.align 2
Cry_Hitmonchan::
	.incbin "sound/direct_sound_samples/cries/hitmonchan.bin"

	.align 2
Cry_Lickitung::
	.incbin "sound/direct_sound_samples/cries/lickitung.bin"

	.align 2
Cry_Koffing::
	.incbin "sound/direct_sound_samples/cries/koffing.bin"

	.align 2
Cry_Weezing::
	.incbin "sound/direct_sound_samples/cries/weezing.bin"

	.align 2
Cry_Rhyhorn::
	.incbin "sound/direct_sound_samples/cries/rhyhorn.bin"

	.align 2
Cry_Rhydon::
	.incbin "sound/direct_sound_samples/cries/rhydon.bin"

	.align 2
Cry_Chansey::
	.incbin "sound/direct_sound_samples/cries/chansey.bin"

	.align 2
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cries/tangela.bin"

	.align 2
Cry_Kangaskhan::
	.incbin "sound/direct_sound_samples/cries/kangaskhan.bin"

	.align 2
Cry_Horsea::
	.incbin "sound/direct_sound_samples/cries/horsea.bin"

	.align 2
Cry_Seadra::
	.incbin "sound/direct_sound_samples/cries/seadra.bin"

	.align 2
Cry_Goldeen::
	.incbin "sound/direct_sound_samples/cries/goldeen.bin"

	.align 2
Cry_Seaking::
	.incbin "sound/direct_sound_samples/cries/seaking.bin"

	.align 2
Cry_Staryu::
	.incbin "sound/direct_sound_samples/cries/staryu.bin"

	.align 2
Cry_Starmie::
	.incbin "sound/direct_sound_samples/cries/starmie.bin"

	.align 2
Cry_MrMime::
	.incbin "sound/direct_sound_samples/cries/mr_mime.bin"

	.align 2
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cries/scyther.bin"

	.align 2
Cry_Jynx::
	.incbin "sound/direct_sound_samples/cries/jynx.bin"

	.align 2
Cry_Electabuzz::
	.incbin "sound/direct_sound_samples/cries/electabuzz.bin"

	.align 2
Cry_Magmar::
	.incbin "sound/direct_sound_samples/cries/magmar.bin"

	.align 2
Cry_Pinsir::
	.incbin "sound/direct_sound_samples/cries/pinsir.bin"

	.align 2
Cry_Tauros::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.align 2
Cry_Magikarp::
	.incbin "sound/direct_sound_samples/cries/magikarp.bin"

	.align 2
Cry_Gyarados::
	.incbin "sound/direct_sound_samples/cries/gyarados.bin"

	.align 2
Cry_Lapras::
	.incbin "sound/direct_sound_samples/cries/lapras.bin"

	.align 2
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cries/ditto.bin"

	.align 2
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cries/eevee.bin"

	.align 2
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cries/vaporeon.bin"

	.align 2
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cries/jolteon.bin"

	.align 2
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cries/flareon.bin"

	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cries/porygon.bin"

	.align 2
Cry_Omanyte::
	.incbin "sound/direct_sound_samples/cries/omanyte.bin"

	.align 2
Cry_Omastar::
	.incbin "sound/direct_sound_samples/cries/omastar.bin"

	.align 2
Cry_Kabuto::
	.incbin "sound/direct_sound_samples/cries/kabuto.bin"

	.align 2
Cry_Kabutops::
	.incbin "sound/direct_sound_samples/cries/kabutops.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cries/aerodactyl.bin"

	.align 2
Cry_Snorlax::
	.incbin "sound/direct_sound_samples/cries/snorlax.bin"

	.align 2
Cry_Articuno::
	.incbin "sound/direct_sound_samples/cries/articuno.bin"

	.align 2
Cry_Zapdos::
	.incbin "sound/direct_sound_samples/cries/zapdos.bin"

	.align 2
Cry_Moltres::
	.incbin "sound/direct_sound_samples/cries/moltres.bin"

	.align 2
Cry_Dratini::
	.incbin "sound/direct_sound_samples/cries/dratini.bin"

	.align 2
Cry_Dragonair::
	.incbin "sound/direct_sound_samples/cries/dragonair.bin"

	.align 2
Cry_Dragonite::
	.incbin "sound/direct_sound_samples/cries/dragonite.bin"

	.align 2
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cries/mewtwo.bin"

	.align 2
Cry_Mew::
	.incbin "sound/direct_sound_samples/cries/mew.bin"


	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_wave_77::
	.incbin "sound/direct_sound_samples/wave_77.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
