VictoryRoad_2F_Text_DawsonIntro::
    .string "If you can get through here,\n"
    .string "you can go meet the ELITE FOUR.$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "No!\n"
    .string "Unbelievable!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "I can beat you when it comes to\n"
    .string "knowledge about POKéMON!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "This here is VICTORY ROAD.\n"
    .string "It's the final test for TRAINERS!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "Atcho!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "If you get stuck, try moving some\n"
    .string "boulders around.$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "Ah, so you wish to challenge the\n"
    .string "ELITE FOUR?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "You got me!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{RIVAL} also came through here.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "Come on!\n"
    .string "I'll whip you!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "I got whipped!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "You earned the right to be on\n"
    .string "VICTORY ROAD…$"

VictoryRoad_2F_Text_ColbyIntro::
    .string "Hey buddy!\n"
    .string "I got pics with all the\n"
    .string "kpop group members!$"

VictoryRoad_2F_Text_ColbyDefeat::
    .string "I have been EV training!$"

VictoryRoad_2F_Text_ColbyPostBattle::
    .string "Good job buddy!$"

VictoryRoad_2F_Text_TylerIntro::
    .string "I havent slept in 2 days!$"

VictoryRoad_2F_Text_TylerDefeat::
    .string "I did it!$"

VictoryRoad_2F_Text_TylerPostBattle::
    .string "I gotta drive 18 hours now!$"

VictoryRoad_2F_Text_LaithanIntro::
    .string "The new Sonic game dropped!$"

VictoryRoad_2F_Text_LaithanDefeat::
    .string "Yeaaa boy!$"

VictoryRoad_2F_Text_LaithanPostBattle::
    .string "Young poop!$"

VictoryRoad_2F_Text_DillonIntro::
    .string "Im gonna cream you!$"

VictoryRoad_2F_Text_DillonDefeat::
    .string "I creamed you!$"

VictoryRoad_2F_Text_DillonPostBattle::
    .string "You creamed me!$ Yahtzeee!$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "Is VICTORY ROAD too tough?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "Well done!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "Many TRAINERS give up their\n"
    .string "challenge here and go home.$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "ギヤーオ！$"

